import Head from 'next/head';
import React from 'react';
import Gallery from '../components/Gallery';
import { GalleryData } from '../components/GalleryData';
import Hero from '../components/Hero';
import Instagram from '../components/Instagram';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Photography Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero heading="Lino's Photography" message='I capture moments in nature to keep them alive.'/>
      <Gallery slides={GalleryData} />
      <Instagram />
    </div>
  );
}
